# frozen_string_literal: true

source "https://rubygems.org"

# Use local gem for testing
gem "jekyll-theme-lanyon", :path => "../"

# gem "jekyll", "~> 3.3"
# gem "jekyll-theme-lanyon"
# group :jekyll_plugins do
#   gem "jekyll-feed"
#   gem "jekyll-paginate"
#   gem "jekyll-sitemap"
# end
