#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
git clone https://${GH_TOKEN}@github.com/noahfkennedy/noahfkennedy.github.io.git --branch gh-pages _site

# build with Jekyll into "_site"
bundle install
bundle exec jekyll build

# push
cd _site
git config user.email "noah.kennedy1@gmail.com"
git config user.name "Noah Kennedy"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages