#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
gpg –keyserver hkp://keys.gnupg.net –recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
git clone https://${GH_TOKEN}@github.com/noahfkennedy/noahfkennedy.github.io.git --branch gh-pages _site

# build with Jekyll into "_site"
bundle install
bundle exec jekyll build

# push
echo spot 1
cd _site
echo spot 2
git config user.email "noah.kennedy1@gmail.com"
echo spot 3
git config user.name "Noah Kennedy"
echo spot 4
git add --all
echo spot 5
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
echo spot 6
git push --force origin gh-pages
echo spot 7